config/routes.rb
Rails.application.routes.draw do

  get 'video/create'
  get 'video/destroy'
  get 'gallery/show'
  devise_for :admins
  #devise_for :users, controllers: { sessions: 'users/sessions' }
  #get 'staticpage/simpleform'
  get '/sitemap.xml.gz', to: redirect("https://tonywebsite.s3.eu-west-3.amazonaws.com/sitemap.xml.gz")
  #get '/sitemap.xml.gz', to: redirect("https://s3-eu-west-1.amazonaws.com/XXXXX-YOUR-BUCKET-XXXXX/sitemap.xml.gz")

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "home#index"

  resources :gig
  resources :admin
  resources :contacts
  resources :category
  resources :repertoire
  resources :bio
  resources :gallery do
    resources :pictures, only: [:create, :destroy]
    resources :video, only: [:create, :destroy]
  end
  

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/models/bio.rb
class Bio < ApplicationRecord

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :repertoires, :dependent => :delete_all
end

app/models/contact.rb
class Contact < ApplicationRecord

  validates :email, 
  :presence => :true,
  :format => { 
    :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
    :message => "must be a valid email address"
  }
validates :message, :presence => :true

end

app/models/gallery.rb
class Gallery < ApplicationRecord
    validates_presence_of :name
    has_many_attached :pictures
    has_many :videos, dependent: :destroy
    accepts_nested_attributes_for :videos,
                                    allow_destroy: true,
                                    reject_if: proc{ |att| att['url'].blank? }
end

app/models/gig.rb
class Gig < ApplicationRecord
    validates_presence_of :title
end

app/models/repertoire.rb
class Repertoire < ApplicationRecord
    validates_presence_of :title
    belongs_to :category
end

app/models/video.rb
class Video < ApplicationRecord
    belongs_to :gallery, optional: true

    def thumbnail(url)
        equalindex = url.index("=")
        id = url[equalindex+1, url.length - equalindex]
        thumbnailurl = "https://img.youtube.com/vi/" + id + "/default.jpg"
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/bio_helper.rb
module BioHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper

    def color(level)
        case level
            when 'notice' then "alert alert-info"
            when 'success' then "alert alert-success"
            when 'error' then "alert alert-error"
            when 'alert' then "alert alert-danger"
        end
    end

end

app/helpers/devise_helper.rb
module DeviseHelper
    def devise_error_messages!
      return '' if resource.errors.empty?
  
      messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

      html = <<-HTML
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
        <strong>
         #{pluralize(resource.errors.count, "error")} must be fixed
        </strong>
        #{messages}
      </div>
      HTML
  
      html.html_safe
    end
  end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/gig_helper.rb
module GigHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/repertoire_helper.rb
module RepertoireHelper
end

app/helpers/sitemaps_helper.rb
module SitemapsHelper
end

app/helpers/staticpage_helper.rb
module StaticpageHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/admin/_articleformaccordian.html.erb
<div class="panel single-accordion">
    <h6><a role="button" class="" aria-expanded="true" aria-controls="collapseOne" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Ajouter un article
            <span class="accor-open"><i class="fa fa-plus" aria-hidden="true"></i></span>
            <span class="accor-close"><i class="fa fa-minus" aria-hidden="true"></i></span>
        </a>
    </h6>
    <div id="collapseOne" class="accordion-content collapse show">
        <h2> prévoir le form pour créer les article de press </h2>
    </div>
</div>

app/views/admin/_bioformaccordian.html.erb
<style>
	trix-editor {
		height: 500px !important;
		max-height: 500px !important;
	  	overflow-y: auto !important;
	}
</style>

<div class="panel single-accordion">
    <h6><a role="button" class="" aria-expanded="true" aria-controls="collapseOne" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Créer ma biographie
            <span class="accor-open"><i class="fa fa-plus" aria-hidden="true"></i></span>
            <span class="accor-close"><i class="fa fa-minus" aria-hidden="true"></i></span>
        </a>
    </h6>
    <div id="collapseOne" class="accordion-content collapse show">
        <!-- ##### Contact Area Start ##### -->
        <section class="contact-form-area section-padding-100-0">
            <div class="container">
            <%= form_for @bio, url: bio_index_path, method: "post" do |f| %>
                <div class="row">      
                    <div class="col-12 col-lg-12">
                        <div class="contact-content mb-100">
                            <!-- Single Contact Info -->
                            <div class="single-contact-info d-flex align-items-center">
                                <div class="icon mr-30">
                                    <span class="icon-user-1"></span>
                                </div>                                                        
                                <%= f.text_field :title, class:"form-control", id:"name", placeholder:"Titre de ma biographie", required: true%>
                            </div>

                            <!-- Single Contact Info -->
                            <div class="single-contact-info d-flex align-items-center">
                                <div class="icon mr-30">
                                    <span class="icon-edit"></span>
                                </div>
                                <%= f.label 'Descripion' %>
                            </div>

                            <div class="justify-content-start">                                          
                                <%= f.trix_editor :content, id:"name", placeholder:"Contenu de ma biographie" %>
                            </div>
                        </div>
                    </div>
                </div>
        
                <div class="row">  
                    <div class="col-12 col-lg-12">
                        <div class="contact-content mb-100">
                            <!-- Single Contact Info -->
                            <div class="single-contact-info d-flex align-items-center">
                                <div class="col-12 text-center">
                                    <%= button_tag( :class => "btn oneMusic-btn mt-30") do %>
                                        Sauvegarder <i class="fa fa-angle-double-right"></i>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
            </div>
        </section>
        <!-- ##### Contact Area End ##### -->
    </div>
</div>

app/views/admin/_biotabaccordian.html.erb
<div class="panel single-accordion">
<h6>
    <a role="button" class="collapsed" aria-expanded="true" aria-controls="collapseTwo" data-parent="#accordion" data-toggle="collapse" href="#collapseTwo">Liste de mes biographies
            <span class="accor-open"><i class="fa fa-plus" aria-hidden="true"></i></span>
            <span class="accor-close"><i class="fa fa-minus" aria-hidden="true"></i></span>
            </a>
</h6>
<div id="collapseTwo" class="accordion-content collapse">
    <div class="col-12">
        <!-- Single Web Icon -->
        <table class="table table-striped table-dark mb-30 mt-30">
            <thead>
                <tr>
                    <th scope="col">id</th>
                    <th scope="col">Titre</th>
                    <th scope="col">Afficher</th>
                    <th scope="col">Editer</th>
                    <th scope="col">Supprimer</th>
                </tr>
            </thead>
            <tbody>
            <% @bios.each do |bio| %>
                <tr>
                    <th scope="row"> <%= bio.id %> </th>
                    <td> <%= link_to bio.title, bio_path(bio), class:"post-title" %> </td>
                    <td> <%= link_to 'Afficher', bio_path(bio) %> </td>
                    <td> <%= link_to 'Editer', edit_bio_path(bio) %> </td>
                    <td> <%= link_to 'Supprimer', bio, method: :delete, class: "delbtn", remote: true %> </td>
                </tr>
            <% end %>
            </tbody>
        </table>
    </div>                                    
</div>
</div>

app/views/admin/_categorytabaccordian.html.erb
<div class="panel single-accordion">
<h6>
    <a role="button" class="collapsed" aria-expanded="true" aria-controls="collapseThree" data-parent="#accordion" data-toggle="collapse" href="#collapseThree">Mes catégories d oeuvres
            <span class="accor-open"><i class="fa fa-plus" aria-hidden="true"></i></span>
            <span class="accor-close"><i class="fa fa-minus" aria-hidden="true"></i></span>
            </a>
</h6>
<div id="collapseThree" class="accordion-content collapse">
    <div class="col-12">
        <!-- Single Web Icon -->
        <table class="table table-striped table-dark mb-30 mt-30">
            <thead>
                <tr>
                    <th scope="col">id</th>
                    <th scope="col">Nom de la catégorie</th>
                    <th scope="col">Nombre d oeuvres</th>
                </tr>
            </thead>
            <tbody>
            <% @categories.each do |cat| %>
                <tr>
                    <th scope="row"> <%= cat.id %> </th>
                    <td> <%= link_to cat.name, repertoire_path(cat), class:"post-title" %> </td>
                    <td> <%= cat.repertoires.count %> </td>
                    <td> <%= link_to 'Afficher', category_path(cat) %> </td>
                    <td> <%= link_to 'Editer', edit_category_path(cat) %> </td>
                    <td> <%= link_to 'Supprimer', cat, method: :delete, class: "delbtn", remote: true %> </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>                                    
</div>
</div>

app/views/admin/_gallerytabaccordian.html.erb
<div class="panel single-accordion">
<h6>
    <a role="button" class="collapsed" aria-expanded="true" aria-controls="collapseThree" data-parent="#accordion" data-toggle="collapse" href="#collapseThree">Mes galeries de photos
            <span class="accor-open"><i class="fa fa-plus" aria-hidden="true"></i></span>
            <span class="accor-close"><i class="fa fa-minus" aria-hidden="true"></i></span>
            </a>
</h6>
<div id="collapseThree" class="accordion-content collapse">
    <div class="col-12">
        <!-- Single Web Icon -->
        <table class="table table-striped table-dark mb-30 mt-30">
            <thead>
                <tr>
                    <th scope="col">id</th>
                    <th scope="col">Nom de la galerie</th>
                    <th scope="col">Nombre de photos</th>
                    <th scope="col">Nombre de vidéos</th>
                    <th scope="col">Editer</th>
                    <th scope="col">Supprimer</th>
                </tr>
            </thead>
            <tbody>
            <% @galleries.each do |gal| %>
                <tr class="tabrow">
                    <th scope="row"> <%= gal.id %> </th>
                    <td> <%= gal.name %> </td>
                    <td> <%= gal.pictures.count %> </td>
                    <td> <%= gal.videos.count %> </td>
                    <td> <%= link_to 'Editer', edit_gallery_path(gal) %>
                    <td> <%= link_to 'Supprimer', gal, method: :delete, class: "delbtn", remote: true %> </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>                                    
</div>
</div>

app/views/admin/_gigformaccordian.html.erb
<div class="panel single-accordion">
    <h6><a role="button" class="" aria-expanded="true" aria-controls="collapseOne" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Ajouter un évènement
            <span class="accor-open"><i class="fa fa-plus" aria-hidden="true"></i></span>
            <span class="accor-close"><i class="fa fa-minus" aria-hidden="true"></i></span>
        </a>
    </h6>
    <div id="collapseOne" class="accordion-content collapse show">
    <!-- ##### Contact Area Start ##### -->
    <section class="contact-form-area section-padding-100-0">
        <div class="container">
            <div class="row">  
            
                <div class="col-12 col-lg-4">
                    <div class="contact-content mb-100">
                    <%= form_for @gig, url: gig_index_path, method: "post" do |f| %>
                            <!-- Single Contact Info -->
                            <div class="single-contact-info d-flex align-items-center">
                                <div class="icon mr-30">
                                    <span class="icon-calendar"></span>
                                </div>
                                <%= f.date_field :date, class:"form-control", id:"name", required: true%>
                            </div>
    
                            <!-- Single Contact Info -->
                            <div class="single-contact-info d-flex align-items-center">
                                <div class="icon mr-30">
                                    <span class="icon-alarm-clock"></span>
                                </div>                                                        
                                <%= f.time_field :time, class:"form-control", id:"name"%>
                            </div>
    
                            <!-- Single Contact Info -->
                            <div class="single-contact-info d-flex align-items-center">
                                <div class="icon mr-30">
                                    <span class="icon-music"></span>
                                </div>                                                        
                                <%= f.text_field :title, class:"form-control", id:"name", placeholder:"Titre", required: true%>
                            </div>
    
                            <!-- Single Contact Info -->
                            <div class="single-contact-info d-flex align-items-center">
                                <div class="icon mr-30">
                                    <span class="icon-home"></span>
                                </div>                                                        
                                <%= f.text_field :place, class:"form-control", id:"name", placeholder:"Lieu"%>
                            </div>
    
                            <!-- Single Contact Info -->
                            <div class="single-contact-info d-flex align-items-center">
                                <div class="icon mr-30">
                                    <span class="icon-placeholder"></span>
                                </div>                                                        
                                <%= f.text_field :adress, class:"form-control", id:"name", placeholder:"Adresse"%>
                            </div>
    
                            <!-- Single Contact Info -->
                            <div class="single-contact-info d-flex align-items-center">
                                <div class="icon mr-30">
                                    <span class="icon-map"></span>
                                </div>
                                <%= f.text_field :mapurl, class:"form-control", id:"name", placeholder:"url de le map"%>
                            </div>
    
    
                            <!-- Single Contact Info -->
                            <div class="single-contact-info d-flex align-items-center">
                                <div class="icon mr-30">
                                    <span class="icon-shopping-cart"></span>
                                </div>
                                <%= f.text_field :ticketurl, class:"form-control", id:"name", placeholder:"url de vente des billets"%>
                            </div>
                    </div>
                </div>
    
                <div class="col-12 col-lg-8">
                    <!-- ##### Google Maps ##### -->
                    <div class="map-area mb-100">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2721.2761970416577!2d3.166399050956415!3d46.99554953787891!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47f04f420b24e6db%3A0x3414e9c637ba3bfa!2sCaf%C3%A9%20Charbon!5e0!3m2!1sfr!2sfr!4v1585992918430!5m2!1sfr!2sfr" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                    </div>
                </div>
    
            </div>
    
            <div class="row">
                <div class="col-12 col-lg-12">
                    <div class="contact-content mb-100">
                        <!-- Single Contact Info -->
                        <div class="single-contact-info d-flex align-items-center">
                            <div class="icon mr-30">
                                <span class="icon-edit  "></span>
                            </div>                                                        
                            <%= f.text_area :description, class:"form-control", id:"name", placeholder:"Desciption de l'évènement"%>
                        </div>
                    </div>
                </div>
            </div>
    
            <div class="row">  
                <div class="col-12 col-lg-12">
                    <div class="contact-content mb-100">
                        <!-- Single Contact Info -->
                        <div class="single-contact-info d-flex align-items-center">
                            <div class="col-12 text-center">
                                <%= button_tag( :class => "btn oneMusic-btn mt-30") do %>
                                    Sauvegarder <i class="fa fa-angle-double-right"></i>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    
            <% end %>
            
        </div>
    </section>
    <!-- ##### Contact Area End ##### -->
    </div>
</div>

app/views/admin/_gigtabaccordian.html.erb
<div class="panel single-accordion">
    <h6>
        <a role="button" class="collapsed" aria-expanded="true" aria-controls="collapseTwo" data-parent="#accordion" data-toggle="collapse" href="#collapseTwo">Liste de mes évènements
                <span class="accor-open"><i class="fa fa-plus" aria-hidden="true"></i></span>
                <span class="accor-close"><i class="fa fa-minus" aria-hidden="true"></i></span>
                </a>
    </h6>
    <div id="collapseTwo" class="accordion-content collapse">
        <div class="col-12">
            <!-- Single Web Icon -->
            <table class="table table-striped table-dark mb-30 mt-30">
                <thead>
                    <tr>
                        <th scope="col">id</th>
                        <th scope="col">Titre</th>
                        <th scope="col">Date</th>
                        <th scope="col">Heure</th>
                        <th scope="col">Editer</th>
                        <th scope="col">Supprimer</th>
                    </tr>
                </thead>
                <tbody>
                <% @gigs.each do |gig| %>
                    <tr>
                        <th scope="row"> <%= gig.id %> </th>
                        <td> <%= link_to gig.title, gig_path(gig), class:"post-title" %> </td>
                        <td> <%= gig.date %> </td>
                        <td> <%= gig.time %> </td>
                        <td> <%= link_to 'Editer', edit_gig_path(gig) %> </td>
                        <td> <%= link_to 'Supprimer',  gig,  method: :delete, class: "delbtn", remote: true %> </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>                                    
    </div>
</div>

app/views/admin/_picformaccordian.html.erb
<div class="panel single-accordion">
    <h6><a role="button" class="" aria-expanded="true" aria-controls="collapseOne" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Ajouter une galerie de photos
            <span class="accor-open"><i class="fa fa-plus" aria-hidden="true"></i></span>
            <span class="accor-close"><i class="fa fa-minus" aria-hidden="true"></i></span>
        </a>
    </h6>
    <div id="collapseOne" class="accordion-content collapse show">
        <!-- ##### Contact Area Start ##### -->
        <section class="contact-form-area section-padding-100-0">
            <div class="container">
            <%= simple_form_for @newgallery, url: gallery_index_path do |f| %>
                <div class="row">            
                    <div class="col-12 col-lg-12">
                        <div class="contact-content mb-100">    

                            <!-- Single Contact Info -->
                            <div class="single-contact-info d-flex align-items-center">
                                <div class="icon mr-30">
                                    <span class="icon-book"></span>
                                </div>    
                                <%= f.text_field :name, class:'form-control', placeholder: 'Saisissez le nom de votre nouvelle galerie de photos', required: true %>
                            </div>

                            <!-- Single Contact Info -->
                            <div class="single-contact-info d-flex align-items-center">
                                <div class="icon mr-30">
                                    <span class="icon-photo-camera"></span>
                                </div>
                                <%= f.drag_and_drop_file_field :pictures, nil, size_limit: 10_000_000 %>
                            </div>

                            <!-- Single Contact Info -->
                            <div class="single-contact-info d-flex align-items-center">
                                <div class="icon mr-30">
                                    <span class="icon-video-camera"></span>
                                </div>
                                <div class="w-100 videos">
                                    <%= f.simple_fields_for :videos do |builder| %>
                                        <%= render 'video_fields', f: builder %>
                                    <% end %>
                                    <%= link_to_add_association 'Ajouter des vidéos', f, :videos, :partial => 'staticpage/video_fields', class: 'btn oneMusic-btn', data: { association_insertion_node: '.videos', association_insertion_method: :append } %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">  
                    <div class="col-12 col-lg-12">
                        <div class="contact-content mb-100">
                            <!-- Single Contact Info -->
                            <div class="single-contact-info d-flex align-items-center">
                                <div class="col-12 text-center">
                                    <%= button_tag( :class => "btn oneMusic-btn mt-30") do %>
                                        Sauvegarder <i class="fa fa-angle-double-right"></i>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            <% end %>
            </div>
        </section>
        <!-- ##### Contact Area End ##### -->
    </div>
</div>

app/views/admin/_repertoiretabaccordian.html.erb
<div class="panel single-accordion">
<h6>
    <a role="button" class="collapsed" aria-expanded="true" aria-controls="collapseTwo" data-parent="#accordion" data-toggle="collapse" href="#collapseTwo">Mon répèrtoire
            <span class="accor-open"><i class="fa fa-plus" aria-hidden="true"></i></span>
            <span class="accor-close"><i class="fa fa-minus" aria-hidden="true"></i></span>
            </a>
</h6>
<div id="collapseTwo" class="accordion-content collapse">
    <div class="col-12">
        <!-- Single Web Icon -->
        <table class="table table-striped table-dark mb-30 mt-30">
            <thead>
                <tr>
                    <th scope="col">id</th>
                    <th scope="col">Titre</th>
                    <th scope="col">Compositeur</th>
                    <th scope="col">Rôle</th>
                    <th scope="col">Catégorie</th>
                    <th scope="col">Afficher</th>
                    <th scope="col">Edition</th>
                    <th scope="col">Supression</th>
                </tr>
            </thead>
            <tbody>
            <% @repertoires.each do |rep| %>
                <tr>
                    <th scope="row"> <%= rep.id %> </th>
                    <td> <%= link_to rep.title, repertoire_path(rep), class:"post-title" %> </td>
                    <td> <%= rep.composer %> </td>
                    <td> <%= rep.role %> </td>
                    <td> <%= rep.category.name %> </td>
                    <td> <%= link_to 'Afficher', repertoire_path(rep) %> </td>
                    <td> <%= link_to 'Editer', edit_repertoire_path(rep) %> </td>
                    <td> <%= link_to 'Supprimer', rep, method: :delete, class: "delbtn", remote: true %> </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>                                    
</div>
</div>

app/views/layouts/_indexfooter.html.erb
<footer class="footer-area">
    <div class="container">
        <div class="row d-flex flex-wrap align-items-center">
            <div class="col-12 col-md-6">
                <!-- Nav brand -->
                <%= link_to image_tag('signature.png'), root_path, class:"nav-brand" %>
                <p style="font-size: 20px"  >Retrouvez-moi ici : <%= link_to (image_tag 'youtube.png'), 'https://www.youtube.com/channel/UCh8d7vvSrjxOp5bhTVRVQvg?view_as=subscriber',  target: :_blank %> <%= link_to (image_tag 'facebook.png'), 'https://www.facebook.com/anthony.rivera.3956',  target: :_blank %> <%= link_to (image_tag 'insta.png'), 'https://www.instagram.com/anthony.ri_ve_ra/',  target: :_blank %></p>
                <p class="copywrite-text">
                    <!-- Link back to Colorlib cannot be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This template is made with
                    <i class="fa fa-heart-o" aria-hidden="true"></i> by
                    <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib cannot be removed. Template is licensed under CC BY 3.0. -->
                </p>
                <p class="copywrite-text">
                    This website uses a colorlib template and is made by flip with <%= link_to (image_tag 'ruby.png'), 'https://github.com/Flip437/tonywebsite.git',  target: :_blank %>
                </p>
            </div>

            <div class="col-12 col-md-6">
                <div class="footer-nav">
                    <ul>
                        <li>
                            <%= link_to "Biographie", bio_index_path %>
                        </li>
                        <li>
                            <%= link_to "Répertoire", repertoire_index_path %>
                        </li>
                        <li>
                            <%= link_to "Galerie", gallery_index_path %>
                        </li>
                        <li>
                            <%= link_to "Agenda", gig_index_path %>
                        </li>
                        <li>
                            <%= link_to "Espace Admin", admin_index_path %>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_indexheader.html.erb
<header class="header-area">
    <!-- Navbar Area -->
    <div class="oneMusic-main-menu">
        <div class="classy-nav-container breakpoint-off">
            <div class="container">
                <!-- Menu -->
                <nav class="classy-navbar justify-content-between" id="oneMusicNav">

                    <!-- Nav brand -->
                    <%= link_to image_tag('signature_small.png'), root_path, class:"nav-brand" %>
            
                    <!-- Navbar Toggler -->
                    <div class="classy-navbar-toggler">
                        <span class="navbarToggler"><span></span><span></span><span></span></span>
                    </div>

                    <!-- Menu -->
                    <div class="classy-menu">

                        <!-- Close Button -->
                        <div class="classycloseIcon">
                            <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                        </div>

                        <!-- Nav Start -->
                        <div class="classynav">
                            <ul>
                                <li> <%= link_to "Biographie", bio_index_path %> </li>
                                <li> <%= link_to "Répertoire", repertoire_index_path %> </li>
                                <li> <%= link_to "Galerie", gallery_index_path %> </li>
                                <li> <%= link_to "Agenda", gig_index_path %> </li>
                    
                                <% if current_admin %>
                                    <li><a href="#">Profil / Déconnexion</a>
                                        <ul class="dropdown">
                                            <li> <%= link_to "Profil", edit_admin_registration_path(current_admin.id) %> </li>
                                            <li> <%= link_to "Déconnexion", destroy_admin_session_path, method: :delete %> </li>
                                            <li> <%= link_to "Espace Admin", admin_index_path %> </li>
                                        </ul>
                                    </li>
                                <% end %>
                            </ul>                       
                        </div>
                        <!-- Nav End -->

                    </div>
                </nav>

                <!-- ##### Alert Area Start ##### -->
                <%= render 'layouts/messages' %>
                <!-- ##### Alert Area End ##### -->

            </div>
        </div>
    </div>
</header>