config/routes.rb
Rails.application.routes.draw do

  get 'video/create'
  get 'video/destroy'
  get 'gallery/show'
  devise_for :admins
  #devise_for :users, controllers: { sessions: 'users/sessions' }
  #get 'staticpage/simpleform'
  get '/sitemap.xml.gz', to: redirect("https://tonywebsite.s3.eu-west-3.amazonaws.com/sitemap.xml.gz")
  #get '/sitemap.xml.gz', to: redirect("https://s3-eu-west-1.amazonaws.com/XXXXX-YOUR-BUCKET-XXXXX/sitemap.xml.gz")

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "home#index"

  resources :gig
  resources :admin
  resources :contacts
  resources :category
  resources :repertoire
  resources :bio
  resources :gallery do
    resources :pictures, only: [:create, :destroy]
    resources :video, only: [:create, :destroy]
  end
  

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bio.rb
class Bio < ApplicationRecord

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :repertoires, :dependent => :delete_all
end

app/models/contact.rb
class Contact < ApplicationRecord

  validates :email, 
  :presence => :true,
  :format => { 
    :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
    :message => "must be a valid email address"
  }
validates :message, :presence => :true

end

app/models/gallery.rb
class Gallery < ApplicationRecord
    validates_presence_of :name
    has_many_attached :pictures
    has_many :videos, dependent: :destroy
    accepts_nested_attributes_for :videos,
                                    allow_destroy: true,
                                    reject_if: proc{ |att| att['url'].blank? }
end

app/models/gig.rb
class Gig < ApplicationRecord
    validates_presence_of :title
end

app/models/repertoire.rb
class Repertoire < ApplicationRecord
    validates_presence_of :title
    belongs_to :category
end

app/models/video.rb
class Video < ApplicationRecord
    belongs_to :gallery, optional: true

    def thumbnail(url)
        equalindex = url.index("=")
        id = url[equalindex+1, url.length - equalindex]
        thumbnailurl = "https://img.youtube.com/vi/" + id + "/default.jpg"
    end
end

app/controllers/bio_controller.rb
class BioController < ApplicationController

  def index
    @page_title = 'Biographie - Anthony Rivera'
    @page_description = "Biographie complète d'Anthony Rivera, chanteur d'opéra"

    set_meta_tags og: {
      title:    @page_title,
      type:     'article',
      image: "http://d1q8yhpgns3eh4.cloudfront.net/assets/core-img/signature_small-034946ef865e1e37df3c663e1fef606b92d929d363f96bee4f814388dc3229c5.png",
      url:      'http://www.anthonyrivera-baryton.fr/bio/',
      site_name: 'Anthony Rivera'
    }

    @bios = Bio.all
    @gigs = []
    Gig.all.each_with_index do |gig, loop|  
        @gigs << gig
        break if loop > 5
    end
  end

  def create
      @bio = Bio.create(title: params[:bio][:title], content: params[:bio][:content])
    if @bio
      flash[:success] = "Vous avez bien ajouté une biographie :)"
      redirect_to admin_index_path
    else
      flash[:error] = "Une erreur s'est produite :("
      redirect_to root_path
    end
  end

  def show
    @bio = Bio.find(params[:id])
  end

  def edit
    @bio = Bio.find(params[:id])
  end

  def update
    @bio = Bio.find(params[:id])
    @bio.content = params[:bio][:content]
    @bio.save
    redirect_to admin_index_path
  end

  def destroy
    @bio = Bio.find(params[:id])
    if @bio.destroy
      respond_to do |format|
        format.js
        format.html { redirect_to admin_index_path }
        end
    else
      flash[:error] = "Une erreur s'est produite :("
      redirect_to admin_index_path
    end
  end

end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController

  def index
    @page_title = 'Gallerie - Anthony Rivera'
    @page_description = "Gallerie complète d'Anthony Rivera, chanteur d'opéra"

    set_meta_tags og: {
      title:    @page_title,
      type:     'article',
      image: "http://d1q8yhpgns3eh4.cloudfront.net/assets/core-img/signature_small-034946ef865e1e37df3c663e1fef606b92d929d363f96bee4f814388dc3229c5.png",
      url:      'http://www.anthonyrivera-baryton.fr/gallery',
      site_name: 'Anthony Rivera'
    }

    @galleries = Gallery.all
  end

  def create
    @gallery = Gallery.new(gallery_params)

    if @gallery.save
      flash[:success] = "Vous avez bien ajouté des photos à votre gallerie :)"
      redirect_to admin_index_path
    else
      flash[:success] = "Une erreur s'est produite :("
      redirect_to admin_index_path
    end 
  end

  def show
    @gallery = Gallery.first
    @pictures = Gallery.first.pictures.all
  end

  def edit
    @gallery = Gallery.find(params[:id])
    @pictures = @gallery.pictures
    @videos = @gallery.videos
  end

  def update
    @gallery = Gallery.find(params[:id])
    @gallery.name = params[:gallery][:name]
    if params[:gallery][:pictures] != nil
      @gallery.pictures.attach(params[:gallery][:pictures])
    end

    if @gallery.save
      flash[:success] = "Vous avez bien modifé la gallerie de photos :)"
      redirect_to admin_index_path
    else
      flash[:error] = "Une erreur s'est produite :("
      redirect_to root_path
    end
  end

  def destroy
    @gallery = Gallery.find(params[:id])
    
    if @gallery.destroy
      flash[:success] = "Vous avez bien supprimé la gallerie de photos :)"
      respond_to do |format|
        format.html { redirect_to admin_index_path }
        format.js
        end
    else
      flash[:error] = "Une erreur s'est produite :("
      redirect_to admin_index_path
    end

  end

  private

  def pictures_params
    params[:gallery].permit(pictures: [])
  end

  def gallery_params
    params
      .require(:gallery)
      .permit(:name, pictures: [], videos_attributes: Video.attribute_names.map(&:to_sym).push(:_destroy))
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/bio_helper.rb
module BioHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper

    def color(level)
        case level
            when 'notice' then "alert alert-info"
            when 'success' then "alert alert-success"
            when 'error' then "alert alert-error"
            when 'alert' then "alert alert-danger"
        end
    end

end

app/helpers/devise_helper.rb
module DeviseHelper
    def devise_error_messages!
      return '' if resource.errors.empty?
  
      messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

      html = <<-HTML
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
        <strong>
         #{pluralize(resource.errors.count, "error")} must be fixed
        </strong>
        #{messages}
      </div>
      HTML
  
      html.html_safe
    end
  end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/gig_helper.rb
module GigHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/repertoire_helper.rb
module RepertoireHelper
end

app/helpers/sitemaps_helper.rb
module SitemapsHelper
end

app/helpers/staticpage_helper.rb
module StaticpageHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/gallery/destroy.js.erb
$(".delbtn").click(function(){
    $(this).closest('tr').remove();
});

app/views/gallery/edit.html.erb
<!-- ##### Breadcumb Area Start ##### -->
<section class="breadcumb-area bg-img bg-overlay" style="background-image: url(<%= asset_path 'writing.jpg' %>);">
    <div class="bradcumbContent">
        <p style="color: black">Modifier la galerie</p>
        <h2 style="color: black"><%=@gallery.name%></h2>
    </div>
</section>
<!-- ##### Breadcumb Area End ##### -->

<!-- ##### Contact Area Start ##### -->
<section class="contact-form-area section-padding-100-0">
    <div class="container">
        <%= form_for @gallery, method: "patch" do |f| %>
        <div class="row">        
            <div class="col-12 col-lg-12">
                <div class="contact-content mb-100">
                <!-- Single Contact Info -->
                <div class="single-contact-info d-flex align-items-center">
                    <div class="icon mr-30">
                        <span class="icon-book"></span>
                        </div>
                        <%= f.text_field :name, class:"form-control", id:"name", cols:"30", placeholder:"Titre"%>
                    </div>

                    <!-- Single Contact Info -->
                    <div class="single-contact-info d-flex align-items-center">
                        <div class="icon mr-30">
                            <span class="icon-photo-camera"></span>
                        </div>
                        <%= f.drag_and_drop_file_field :pictures, "Déposer vos photos ici", size_limit: 10_000_000 %>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">  
            <div class="col-12 col-lg-12">
                <div class="contact-content mb-100">
                    <!-- Single Contact Info -->
                    <div class="single-contact-info d-flex align-items-center">
                        <div class="col-12 text-center">
                            <%= button_tag( :class => "btn oneMusic-btn mt-30") do %>
                                Sauvegarder <i class="fa fa-angle-double-right"></i>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <% end %>

        <div class="row">        
            <div class="col-12 col-lg-12">
                <div class="contact-content mb-100">
                    <!-- Single Contact Info -->
                    <div class="single-contact-info d-flex align-items-center">
                        <div class="icon mr-30">
                            <span class="icon-photo-camera"></span>
                        </div>
                        <div class="row">
                            <% @pictures.each do |pic| %>
                                <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                                    <%= image_tag(pic, class: 'zoom img-fluid') %>
                                    <%= link_to 'Supprimer', gallery_picture_path(@gallery, pic), method: :delete, data: { confirm: 'Etes vous sur de vouloir supprimer cette photo?' } %>
                                </div>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">        
            <div class="col-12 col-lg-12">
                <div class="contact-content mb-100">
                    <!-- Single Contact Info -->
                    <div class="single-contact-info d-flex align-items-center">
                        <div class="icon mr-30">
                            <span class="icon-video-camera"></span>
                        </div>
                        <div class="row">
                            <% @videos.each do |vid| %>
                                <div class="thumb">                               
                                    <div class="single-album-area wow fadeInUp" data-wow-delay="100ms">
                                        <div class="album-thumb">
                                            <%= image_tag('youtube.jpg', class: 'zoom img-fluid') %>
                                            <!-- Play Icon -->
                                            <div class="play-icon">
                                                <%= content_tag(:a, content_tag(:span,"", class: "icon-play-button"), :href => "#{vid.url}", class: "video--play--btn") %>
                                            </div>
                                        </div>
                                    </div>
                                    <p> <%= vid.name %> </p> <br>
                                    <%= link_to 'Supprimer', gallery_video_path(@gallery, vid), method: :delete, data: { confirm: 'Etes vous sur de vouloir supprimer cette vidéo?' } %>
                                </div>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">        
            <div class="col-12 col-lg-12">
                <div class="contact-content mb-100">
                    <!-- Single Contact Info -->
                    <div class="single-contact-info d-flex align-items-center">
                        <div class="icon mr-30">
                            <span class="icon-trash"></span>
                        </div>
                        <%= link_to 'Supprimer la galerie', @gallery, method: :delete, data: { confirm: 'Etes vous sur de vouloir supprimer cette galerie?' } %>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>
<!-- ##### Contact Area End ##### -->

app/views/gallery/index.html.erb
<!-- ##### Breadcumb Area Start ##### -->
<section class="breadcumb-area bg-img bg-overlay" style="background-image: url(<%= asset_path 'curtain.jpg' %>);">
    <div class="bradcumbContent" style="background: rgba(0, 0, 0, 0.0)">
        <p>Me reconnaitre</p>
        <h2>Galerie</h2>
    </div>
</section> 

<!-- ##### Elements Area Start ##### -->
<section class="blog-area section-padding-100">
    <div class="container">
        <div class="row">
            <!-- ##### Uploaded pictures Area Start ##### -->
                <div class="col-12 col-lg-12">
                <% if Gallery.exists? %>
                    <% @galleries.each_with_index do |gal, index| %>
                    <div class="accordions mb-50" id="accordion" role="tablist" aria-multiselectable="true">
                        <!-- single accordian area -->  
                        <div class="panel single-accordion" style="background: transparent">
                            <h6>
                                <a role="button" class="" aria-expanded="true" aria-controls="collapse<%= index %>" data-parent="#accordion" data-toggle="collapse" href="#collapse<%= index %>"><%= gal.name %>
                                        <span class="accor-open"><i class="fa fa-plus" aria-hidden="true"></i></span>
                                        <span class="accor-close"><i class="fa fa-minus" aria-hidden="true"></i></span>
                                        </a>
                            </h6>
                            <div id="collapse<%= index %>" class="accordion-content collapse show">
                            <!-- Images Area Start -->
                                <div class="col-12">                        
                                    <div class="row pt-5 gallery">
                                        <% if gal.pictures.attached? %>
                                            <% gal.pictures.each do |pic| %>
                                                <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                                                    <%= link_to image_tag(pic, class: 'zoom img-fluid'), pic, class: 'fancybox', rel: 'lightbox[index]' %>
                                                </div>
                                            <% end %>
                                        <%end%>

                                        <% if gal.videos != nil %>
                                            <% gal.videos.each do |vid| %>
                                                <div class="col-lg-3 col-md-4 col-xs-6 thumb">                               
                                                    <div class="single-album-area wow fadeInUp" data-wow-delay="100ms">
                                                        <div class="album-thumb">
                                                            <%= image_tag(vid.thumbnail(vid.url), class: 'zoom img-fluid') %>
                                                            <!-- Play Icon -->
                                                            <div class="play-icon">
                                                                <%= content_tag(:a, content_tag(:span,"", class: "icon-play-button"), :href => "#{vid.url}", class: "video--play--btn") %>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            <%end%>
                                        <%end%>                           
                                    </div>
                                </div>
                            <!-- Images Area End -->                                  
                            </div>
                        </div>
                    </div>
                    <% end %>
                <% else %>
                    <!-- Single Post Start -->
                    <div class="single-blog-post mb-100 wow fadeInUp" data-wow-delay="100ms">
                        <!-- Blog Content -->
                        <div class="blog-content">
                            <!-- Post Title -->
                            <div class="post-title">
                                <h3> Vous n'avez pas de galerie pour l'instant </h3>
                            </div>
                        </div>
                    </div>
                <% end %>
                </div>
            <!-- ##### Uploaded pictures Area End ##### -->
        </div>
    </div>
</section>
<!-- ***** Elements Area End ***** -->